name: jack wink
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24004461569711566
title: jack wink
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f5e0'
    - '#562e0a'
    - '#866947'
    - '#a39171'
    - '#c8b897'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
